-- SQL para criar a tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
 FUNC_ID INTEGER PRIMARY KEY,
 FUNC_NOME VARCHAR(45) NULL,
 FUNC_STATUS INTEGER
);

-- SQL para criar a tabela PROCESSO
CREATE TABLE TIPO_PROCESSO (
 TIPR_ID INTEGER PRIMARY KEY,
 TIPR_NOME VARCHAR(45) NULL,
 TIPR_DESCRICAO VARCHAR(250) NULL,
 TIPR_STATUS INTEGER
 );

-- SQL para criar a tabela MOVIMENTO
CREATE TABLE MOVIMENTO (
 MOVI_ID INTEGER PRIMARY KEY,
 MOVI_DATE DATE NOT NULL,
 MOVI_PESO_ENTRADA DOUBLE NULL,
 MOVI_PESO_SAIDA DOUBLE NULL,
 MOVI_DESC VARCHAR(300) NULL,
 MOVI_TIPR_ID INTEGER NULL,
 MOVI_FUNC_ID INTEGER NULL,
 CONSTRAINT MOVI_TIPR_ID
 FOREIGN KEY (MOVI_TIPR_ID)
 REFERENCES TIPO_PROCESSO (TIPR_ID),
 CONSTRAINT MOVI_FUNC_ID
 FOREIGN KEY (MOVI_FUNC_ID)
 REFERENCES FUNCIONARIO (FUNC_ID)
);

-- SQL para criar a tabela TIPO_MATERIA_PRIMA
CREATE TABLE TIPO_MATERIA_PRIMA (
 TIMP_ID INTEGER PRIMARY KEY,
 TIMP_NOME VARCHAR(45) NULL,
 TIMP_DESCRICAO VARCHAR(250) NULL,
 TIMP_STATUS INTEGER
 );

-- SQL para criar a tabela MATERIA_PRIMA
CREATE TABLE MOVIMENTO_MATERIA_PRIMA (
 MATE_ID INTEGER PRIMARY KEY,
 MATE_DATA DATE NULL,
 MATE_PESO DOUBLE NULL,
 MATE_DESCRICAO VARCHAR(100) NULL,
 MATE_ENTRADA_SAIDA INTEGER NOT NULL,
 MATE_TPMP_ID INTEGER NULL,
 CONSTRAINT MATE_TPMP_ID
 FOREIGN KEY (MATE_TPMP_ID)
 REFERENCES TIPO_MATERIA_PRIMA (TIMP_ID)
);
